### ISSUE TITLE
assertNoLogs

### ISSUE THREAD

**Issue by jayvdb** [chadrosenquist/logging-test-case#4]
assertLogs raises an exception if no messages where logged, which makes it a bit annoying to assert that there were no logs with the option of reporting whatever logs where unexpectedly encountered.

It would be nice to have a `self.assertNoLogs` to complement `self.assertLogs`

**Comment by jayvdb** [comment]
Some prior art for it at https://github.com/Qiskit/aqua/blob/master/test/common.py

https://github.com/search?l=Python&q=assertNoLogs&type=Code doesnt show many others doing this.

**Comment by chadrosenquist** [comment]
Yeah, that is a great idea to add `self.assertNoLogs`.  I can see it being very useful to verify certain logging only occurs in a development/debug environment and not in a production environment.
